# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kudoy
email: info@elyonstrategies.com
description: > # this means to ignore newlines until "baseurl:"
  Kudoy is an easily accessed, quickly executed, concise method to move from challenge to strategic resolution in 12 online steps. The process is reusable, refinable, and extensible to the largest problem. The result is a one page strategic plan graphic that captures all of the vital information associated with a vision and the strategies that will achieve it.  
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

imagedirectory: "/kudoy/assets/img"
icondirectory: "/kudoy/assets/icons"
favdirectory: "/kudoy/assets/fav"

sass:
    style: compressed

# Build settings
markdown: kramdown
